-- Add CHANGE_ROOM to AuditAction enum
-- GL-002: changement de chambre pendant un séjour (StayService.changeRoom)
--
-- Correction (avant merge) : la version initiale de cette migration listait
-- un instantané erroné de AuditAction — omettant VALIDATE_PURCHASE_ORDER et
-- REOPEN_HOUSEKEEPING_TASK (présents dans schema.prisma), et introduisant à
-- tort DELETE_ROOM_TYPE, une valeur qui n'existe dans aucune version de
-- schema.prisma ni dans aucune autre migration du dépôt (recherchée dans
-- tout l'historique de origin/main : absente). Un MODIFY ENUM qui omet une
-- valeur réellement utilisée la supprime silencieusement de la colonne
-- MySQL ("Data truncated for column 'action'" à la première écriture d'une
-- valeur manquante, constaté en CI sur purchase-orders.e2e-spec.ts). La
-- liste ci-dessous correspond exactement à l'énumération AuditAction
-- actuelle de schema.prisma (53 valeurs), sans ajout ni omission.
ALTER TABLE `AuditLog` MODIFY `action` ENUM('ADJUST_TIME_SHIFT','AUTO_CLOSE_TIME_SHIFT','BLACKLIST_CLIENT','CANCEL_FOLIO_LINE','CANCEL_HOUSEKEEPING_TASK','CANCEL_PURCHASE_ORDER','CANCEL_RESERVATION','CHANGE_CATEGORY','CHANGE_ROOM','CREATE_CANCELLATION_POLICY','CREATE_CHANNEL_ROOM_TYPE_MAPPING','CREATE_CREDIT_NOTE','CREATE_DEPOSIT','CREATE_NOTIFICATION_TEMPLATE','CREATE_POLICE_RECORD','CREATE_PURCHASE_ORDER','CREATE_RATE_RESTRICTION','CREATE_RESTAURANT_CHARGE','CREATE_ROOM','CREATE_ROOM_TYPE','CREATE_SEASON_RATE','CREATE_SUPPLIER','CREATE_TAX_RATE','DELETE_CHANNEL_ROOM_TYPE_MAPPING','DELETE_RATE_RESTRICTION','DELETE_ROOM','DELETE_SEASON_RATE','DELETE_SUPPLIER','EXCLUDE_FOLIO_TAX','FORCE_CHECKOUT','FORCE_CHECKOUT_RESTAURANT','IMPUTE_DEPOSIT','INVALIDATE_TIME_SHIFT','MARK_NO_SHOW','REASSIGN_HOUSEKEEPING_TASK','REFUND_DEPOSIT','REFUSE_HOUSEKEEPING_TASK','REOPEN_HOUSEKEEPING_TASK','SUBMIT_PURCHASE_ORDER','UPDATE_CANCELLATION_POLICY','UPDATE_HOTEL_CONFIG','UPDATE_NOTIFICATION_TEMPLATE','UPDATE_PRICE','UPDATE_PURCHASE_ORDER','UPDATE_RATE_RESTRICTION','UPDATE_ROOM','UPDATE_ROOM_TYPE','UPDATE_SEASON_RATE','UPDATE_SUPPLIER','UPDATE_TAX_RATE','VALIDATE_HOUSEKEEPING_TASK','VALIDATE_PAYSLIP','VALIDATE_PURCHASE_ORDER') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
