/*
  Warnings:

  - Made the column `action` on table `AuditLog` required. This step will fail if there are existing NULL values in that column.

*/
-- AlterTable
ALTER TABLE `AuditLog` MODIFY `action` ENUM('CHANGE_CATEGORY', 'BLACKLIST_CLIENT', 'UPDATE_PRICE', 'CANCEL_RESERVATION', 'UPDATE_HOTEL_CONFIG', 'UPDATE_TAX_RATE', 'CREATE_TAX_RATE', 'CREATE_SEASON_RATE', 'UPDATE_SEASON_RATE', 'DELETE_SEASON_RATE', 'ADJUST_TIME_SHIFT', 'INVALIDATE_TIME_SHIFT', 'AUTO_CLOSE_TIME_SHIFT', 'VALIDATE_PAYSLIP', 'CREATE_POLICE_RECORD', 'CREATE_DEPOSIT', 'IMPUTE_DEPOSIT', 'REFUND_DEPOSIT', 'EXCLUDE_FOLIO_TAX', 'CREATE_CANCELLATION_POLICY', 'UPDATE_CANCELLATION_POLICY', 'MARK_NO_SHOW', 'CREATE_RATE_RESTRICTION', 'UPDATE_RATE_RESTRICTION', 'DELETE_RATE_RESTRICTION', 'CREATE_NOTIFICATION_TEMPLATE', 'UPDATE_NOTIFICATION_TEMPLATE', 'CREATE_CHANNEL_ROOM_TYPE_MAPPING', 'DELETE_CHANNEL_ROOM_TYPE_MAPPING', 'CREATE_CREDIT_NOTE', 'FORCE_CHECKOUT', 'CREATE_ROOM', 'UPDATE_ROOM', 'DELETE_ROOM', 'CREATE_ROOM_TYPE', 'UPDATE_ROOM_TYPE', 'CANCEL_FOLIO_LINE', 'CREATE_RESTAURANT_CHARGE', 'FORCE_CHECKOUT_RESTAURANT', 'CREATE_SUPPLIER', 'UPDATE_SUPPLIER', 'DELETE_SUPPLIER', 'CREATE_PURCHASE_ORDER', 'UPDATE_PURCHASE_ORDER', 'SUBMIT_PURCHASE_ORDER', 'VALIDATE_PURCHASE_ORDER', 'CANCEL_PURCHASE_ORDER', 'REASSIGN_HOUSEKEEPING_TASK', 'CANCEL_HOUSEKEEPING_TASK', 'VALIDATE_HOUSEKEEPING_TASK', 'REFUSE_HOUSEKEEPING_TASK', 'REOPEN_HOUSEKEEPING_TASK', 'CHANGE_ROOM', 'EXTEND_STAY', 'RECONCILE_TAXE_SEJOUR') NOT NULL;

-- AlterTable
ALTER TABLE `Reservation` ADD COLUMN `nombreOccupants` INTEGER NULL;

-- AlterTable
ALTER TABLE `Stay` ADD COLUMN `nombreOccupants` INTEGER NULL;
