-- FIN-102B (ADR-008, INV-TEMP-001) — timing de matérialisation de
-- TAXE_SEJOUR : ajout de l'occupation réelle sur Reservation/Stay
-- (nullable, aucun backfill — les séjours historiques restent NULL,
-- marqueur legacy consommé uniquement par le fallback de
-- BillingService.generateInvoice, voir schema.prisma) et de la nouvelle
-- AuditAction dédiée à la réconciliation de départ anticipé.

-- AlterTable
ALTER TABLE `Reservation` ADD COLUMN `nombreOccupants` INTEGER NULL;

-- AlterTable
ALTER TABLE `Stay` ADD COLUMN `nombreOccupants` INTEGER NULL;

-- AlterTable
-- Liste complète (55 valeurs) revalidée contre schema.prisma au moment de la
-- génération (voir la migration EXTEND_STAY précédente et sa leçon : un
-- MODIFY ENUM qui omet une valeur réellement utilisée la supprime
-- silencieusement de la colonne MySQL). Aucun ajout ni omission au-delà de
-- l'ajout de RECONCILE_TAXE_SEJOUR par rapport à la migration précédente.
ALTER TABLE `AuditLog` MODIFY `action` ENUM('ADJUST_TIME_SHIFT','AUTO_CLOSE_TIME_SHIFT','BLACKLIST_CLIENT','CANCEL_FOLIO_LINE','CANCEL_HOUSEKEEPING_TASK','CANCEL_PURCHASE_ORDER','CANCEL_RESERVATION','CHANGE_CATEGORY','CHANGE_ROOM','CREATE_CANCELLATION_POLICY','CREATE_CHANNEL_ROOM_TYPE_MAPPING','CREATE_CREDIT_NOTE','CREATE_DEPOSIT','CREATE_NOTIFICATION_TEMPLATE','CREATE_POLICE_RECORD','CREATE_PURCHASE_ORDER','CREATE_RATE_RESTRICTION','CREATE_RESTAURANT_CHARGE','CREATE_ROOM','CREATE_ROOM_TYPE','CREATE_SEASON_RATE','CREATE_SUPPLIER','CREATE_TAX_RATE','DELETE_CHANNEL_ROOM_TYPE_MAPPING','DELETE_RATE_RESTRICTION','DELETE_ROOM','DELETE_SEASON_RATE','DELETE_SUPPLIER','EXCLUDE_FOLIO_TAX','EXTEND_STAY','FORCE_CHECKOUT','FORCE_CHECKOUT_RESTAURANT','IMPUTE_DEPOSIT','INVALIDATE_TIME_SHIFT','MARK_NO_SHOW','REASSIGN_HOUSEKEEPING_TASK','RECONCILE_TAXE_SEJOUR','REFUND_DEPOSIT','REFUSE_HOUSEKEEPING_TASK','REOPEN_HOUSEKEEPING_TASK','SUBMIT_PURCHASE_ORDER','UPDATE_CANCELLATION_POLICY','UPDATE_HOTEL_CONFIG','UPDATE_NOTIFICATION_TEMPLATE','UPDATE_PRICE','UPDATE_PURCHASE_ORDER','UPDATE_RATE_RESTRICTION','UPDATE_ROOM','UPDATE_ROOM_TYPE','UPDATE_SEASON_RATE','UPDATE_SUPPLIER','UPDATE_TAX_RATE','VALIDATE_HOUSEKEEPING_TASK','VALIDATE_PAYSLIP','VALIDATE_PURCHASE_ORDER') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
