-- AlterTable
ALTER TABLE `Reservation` ADD COLUMN `formule` ENUM('ROOM_ONLY', 'BED_AND_BREAKFAST', 'HALF_BOARD', 'FULL_BOARD') NOT NULL DEFAULT 'BED_AND_BREAKFAST';

-- AlterTable
ALTER TABLE `RoomType` ADD COLUMN `prixDemiPension` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `prixPensionComplete` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `prixPetitDejeuner` DECIMAL(10, 2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `Stay` ADD COLUMN `formule` ENUM('ROOM_ONLY', 'BED_AND_BREAKFAST', 'HALF_BOARD', 'FULL_BOARD') NOT NULL DEFAULT 'BED_AND_BREAKFAST';
