-- CreateTable
CREATE TABLE `RoomStatusLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `roomId` INTEGER NOT NULL,
    `ancienStatut` ENUM('LIBRE_PROPRE', 'RESERVEE', 'OCCUPEE', 'DEPART_PREVU', 'A_NETTOYER', 'EN_NETTOYAGE', 'EN_MAINTENANCE') NOT NULL,
    `nouveauStatut` ENUM('LIBRE_PROPRE', 'RESERVEE', 'OCCUPEE', 'DEPART_PREVU', 'A_NETTOYER', 'EN_NETTOYAGE', 'EN_MAINTENANCE') NOT NULL,
    `motif` VARCHAR(191) NULL,
    `userId` INTEGER NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `RoomStatusLog` ADD CONSTRAINT `RoomStatusLog_roomId_fkey` FOREIGN KEY (`roomId`) REFERENCES `Room`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
